name = "data-gateway"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB_MEMCARE"
database_name = "openclaw-memcare"
database_id = "943932bc-653e-4fb5-88b6-4eff9895fcbc"

[[d1_databases]]
binding = "DB_GRAPH"
database_name = "openclaw-graph"
database_id = "f60860bc-9808-4ade-989d-6840accbfc50"

[observability]
enabled = true
